### ISSUE TITLE
javascript frameworks

### ISSUE THREAD

**Issue by WilsonMonkey** [Canbanizers/Canban#19]
look for different useful frameworks (MVC, Templating, fancy design...), for instance emberjs, meteorjs.

**Comment by ghost** [comment]
WillsonMonkey and I discussed about MeteorJS and Ember.js. We decided, that Ember.js fits our purposes better than MeteorJS. Please comment this issue, until next Wednesday, with your thoughts about the frameworks you checked out. closed #27

**Comment by WilsonMonkey** [comment]
CLOSED
We will use Ember.js from now on.
