### ISSUE TITLE
Issues for Bug Tracking

### ISSUE THREAD

**Issue by ghost** [Canbanizers/Canban#2]
I would propse to use these issues for bugtracking/feature suggestions since we don't have something like youtrack. So every time you find a bug - and can't fix it immediately - or have a feature suggestion, please open an issue here.

**Comment by WilsonMonkey** [comment]
okay sounds good. do you know if we can assign more than one person to an issue? maybe this 'milestones' stuff is interesting too? especially for big features, refactorings and so on...

**Comment by WilsonMonkey** [comment]
take a look: https://github.com/blog/831-issues-2-0-the-next-generation
