### ISSUE TITLE
remove .idea

### ISSUE THREAD

**Issue by ghost** [Canbanizers/Canban#26]
remove the .idea directory from the reposetory

**Comment by WilsonMonkey** [comment]
remove dir

You have to rebase the master if you have any local changes!!!
Otherwise you can update the project.

**Comment by WilsonMonkey** [comment]
When all of you rebased and updated the project without conflicts, please close this ticket.

**Comment by ghost** [comment]
I just recognized, that I can still see the .idea directory.
