### ISSUE TITLE
DBcredentials Problem

### ISSUE THREAD

**Issue by janz93** [Canbanizers/Canban#43]
relates to closed issues #9 

Probably due configuration Problems my
db_credentials.xml can't be found within the relative path.

My suggestion would be:

1) check in the CredentialsReader class at the getCredentials() method if the file exists and otherwise throw an exception 

2) is it possible to set up an application root path so we don't have to work with an relative path?

**Comment by WilsonMonkey** [comment]
i will fix it asap.
