### ISSUE TITLE
Use of ember-simple-auth Plugin

### ISSUE THREAD

**Issue by janz93** [Canbanizers/Canban#45]
relates to #21 

Make use of the ember-simple-auth Plugin

it's an token based login method.

https://github.com/simplabs/ember-simple-auth

My opinion to it.

pros:
- is already been built and tested
- makes use a standards 

contra:
- have to modify user database
- not the best documentation

**Comment by WilsonMonkey** [comment]
why we have to modify the user database?
can you upload an example-application, if you want to try it out?

**Comment by WilsonMonkey** [comment]
also the documentation seems to me very detailed.
