### ISSUE TITLE
Login Idea question

### ISSUE THREAD

**Issue by janz93** [Canbanizers/Canban#48]
Related to #21 

This my idea: 
![login](https://f.cloud.github.com/assets/5300559/2000729/642a607c-8566-11e3-8fb9-e82702886d78.PNG)

It's late but my question is:
1) Is in the Post request a man in the middle able to get the ClientHash output?
2) If he is then he could make his own login sucessful Login request with ClientHash?

ref:https://crackstation.net/hashing-security.htm

**Comment by WilsonMonkey** [comment]
Hey Jan. Please don't think about stuff like securete to much, for now. Don't forget that our teacher said, that the backend isn't important for our grade. 
PS: In login process i would use https, like for every request with securety conserns..
