### ISSUE TITLE
Marktanalyse durchführen 2

### ISSUE THREAD

**Issue by ghost** [Canbanizers/Canban#54]
- Absatzmöglichkeiten erkennen
- Festlegung der Zielgruppen
- Risiken einschätzen

**Comment by janz93** [comment]
Könnte ihr mir die Sachen für GProz hochladen.
Sodass ich Sie am Wochenende fertig mache oder man trifft sich und macht die gemeinsam fertig.
Ist mir egal.

**Comment by WilsonMonkey** [comment]
Hi,
sorry das ich mich erst jetzt melde. 
Wir werden das heute fertig machen und dann hochladen. Falls du es dann morgen bzw. übermorgen nicht mehr schaffst, wäre das denke ich auch ok wenn du das bis Ende nächster Woche erledigst.

**Comment by ghost** [comment]
Jo, da stimme ich Wilson zu. Gerade da ich auch "schuld" daran bin, dass wir es letztes WE nicht geschaft haben, da ich vergessen hatte das ich meiner Mutter versprochen habe zu ihr zu kommen.
