### ISSUE TITLE
can't choose jan as assignee

### ISSUE THREAD

**Issue by WilsonMonkey** [Canbanizers/Canban#6]
can't assign issues to jan. maybe he have to be an admin too? also we have to invite christian, he can checkout the project and get familiar with github.

**Comment by ghost** [comment]
maybe jan hasn't accepted the invitation to Canbanizers yet? Do you know if christian already created an GitHub account?

**Comment by WilsonMonkey** [comment]
No, i will talk to him next week after finishing the marketing-presentation.
