### ISSUE TITLE
implement group-tasks

### ISSUE THREAD

**Issue by WilsonMonkey** [Canbanizers/Canban#76]
# add group
## Formfields:
- groupname
- grouppassword
- number of boardcolumns/naming of boardcolumns ?
- Work in Progress ?
- ...
# join group
## Formfields:
- groupname
- grouppassword
# edit group (group-admin only)
## Formfields:
- edit groupname
- edit grouppassword
- kick users
- add/invite users
- edit number of boardcolumns/naming of boardcolumns ?
- edit Work in Progress ?
- ...
# leave group
## Button:
- leave group
# delete group (group-admin only)
## Button:
- delete group
## Prompt:
- confirm grouppassword

**Comment by ghost** [comment]
If you have kick user, you should also have add/invite user, i gues.

**Comment by WilsonMonkey** [comment]
invite could be difficult, because we need a messagestream for this?
add user could be useful, i will record it.
